services:
  mongo:
    image: mongo
    container_name: central-pet-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - central-pet-network

  backend:
    image: central-pet-back:0.1.0
    container_name: central-pet-backend
    ports:
      - "5000:5000"
    environment:
      - MONGOURI=mongodb://central-pet-mongo:27017/central-pet
    depends_on:
      - mongo
    networks:
      - central-pet-network

  frontend:
    image: central-pet-front:0.1.0
    container_name: central-pet-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_REACT_APP_API_BASE_URL=http://central-pet-backend:5000
    depends_on:
      - backend
    networks:
      - central-pet-network

volumes:
  mongo-data:

networks:
  central-pet-network:
    driver: bridge
